#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t viper"

$L "    ▌ ▐·▪   ▄▄▄·▄▄▄ .▄▄▄        .▄▄ ·   "
$L "   ▪█·█▌██ ▐█ ▄█▀▄.▀·▀▄ █·▪     ▐█ ▀.   "
$L "   ▐█▐█•▐█· ██▀·▐▀▀▪▄▐▀▀▄  ▄█▀▄ ▄▀▀▀█▄  "
$L "    ███ ▐█▌▐█▪·•▐█▄▄▌▐█•█▌▐█▌.▐▌▐█▄▪▐█  "
$L "   . ▀  ▀▀▀.▀    ▀▀▀ .▀  ▀ ▀█▄▀▪ ▀▀▀▀   "
$L "Welcome to Android `getprop ro.build.version.release` / Viper0S-`getprop ro.viper.version`";