#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t viper"

$L "        _                  ___  __    "
$L " /\   /(_)_ __   ___ _ __ /___\/ _\   "
$L " \ \ / / | '_ \ / _ \ '__//  //\ \    "
$L "  \ V /| | |_) |  __/ | / \_// _\ \   "
$L "   \_/ |_| .__/ \___|_| \___/  \__/   "
$L "         |_|                          "
$L "Welcome to Android `getprop ro.build.version.release` / ViperOS-`getprop ro.viper.version`";